### Listar áreas
GET https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/areas

### Criar área
POST https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/areas
Content-Type: application/json

{
  "nome": "Design"
}

### Buscar área
GET https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/areas/1

### Atualizar área
PUT https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/areas/1
Content-Type: application/json

{
  "nome": "Desenvolvimento Web"
}

### Deletar área
DELETE https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/areas/1