### Listar todas as empresas
GET http://localhost:8080/empresas

### Buscar empresa por ID
GET http://localhost:8080/empresas/1

### Adicionar nova empresa
POST http://localhost:8080/empresas
Content-Type: application/json

{
  "nome": "Nova Empresa Ltda",
  "cnpj": "12.111.222/0001-33",
  "emailContato": "contato@novaempresa.com"
}

### Atualizar empresa existente
PUT http://localhost:8080/empresas/2
Content-Type: application/json

{
  "nome": "Beta Comércio Atualizado ME",
  "cnpj": "98.765.432/0001-10",
  "emailContato": "novo@beta.com"
}

### Deletar empresa
DELETE http://localhost:8080/empresas/3
