### Listar empresas
GET https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/empresas

### Criar empresa
POST https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/empresas
Content-Type: application/json

{
  "nomeFantasia": "Empresa Alfa LTDA",
  "cnpj": "12.345.678/0001-90",
  "emailContato": "contato@empresa-alfa.com",
  "endereco": "Av A, 100",
  "descricao": "Alfa description"
}

### Buscar empresa
GET https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/empresas/1

### Atualizar empresa
PUT https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/empresas/1
Content-Type: application/json

{
  "nomeFantasia": "Empresa Alfa Atualizada",
  "cnpj": "12.345.678/0001-90",
  "emailContato": "novo@empresa-alfa.com",
  "endereco": "Av A, 100",
  "descricao": "Atualizada"
}

### Deletar empresa
DELETE https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/empresas/1
