GET http://localhost:8080/estudantes

POST http://localhost:8080/estudantes
Content-Type: application/json

{
  "nome":"João Silva",
  "email":"joao@email.com",
  "nascimento":"2004-05-01",
  "anoIngresso":2022
}

GET http://localhost:8080/estudantes/1

PUT http://localhost:8080/estudantes/1
Content-Type: application/json

{
  "nome":"João S.",
  "email":"joao@novo.com",
  "nascimento":"2004-05-01",
  "anoIngresso":2022
}

DELETE http://localhost:8080/estudantes/1
