### Listar inscrições
GET http://localhost:8080/inscricoes

### Criar inscrição
POST http://localhost:8080/inscricoes
Content-Type: application/json

{
  "estudanteId": "1",
  "vagaId": "1",
  "mensagemApresentacao": "Tenho experiência com Java."
}

### Buscar inscrição
GET http://localhost:8080/inscricoes/1

### Deletar inscrição
DELETE http://localhost:8080/inscricoes/1