### Listar inscrições
GET https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/inscricoes

### Criar inscrição
POST https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/inscricoes
Content-Type: application/json

{
  "estudanteId": "1",
  "vagaId": "1",
  "mensagemApresentacao": "Tenho experiência com Java."
}

### Buscar inscrição
GET https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/inscricoes/1

### Deletar inscrição
DELETE https://improved-guacamole-4jp795r7w4xhq55g-8080.app.github.dev/inscricoes/1