### Listar todas as vagas
GET http://localhost:8080/vagas

### Buscar vaga por ID
GET http://localhost:8080/vagas/1

### Adicionar nova vaga
POST http://localhost:8080/vagas
Content-Type: application/json

{
  "titulo": "Estagiário de TI",
  "descricao": "Suporte a projetos internos e testes de software.",
  "publicacao": "2025-10-15",
  "ativo": true,
  "idEmpresa": 3
}

### Atualizar vaga existente
PUT http://localhost:8080/vagas/2
Content-Type: application/json

{
  "titulo": "Analista de Suporte Técnico Jr",
  "descricao": "Atendimento remoto e manutenção de sistemas.",
  "publicacao": "2025-09-27",
  "ativo": true,
  "idEmpresa": 2
}

### Deletar vaga
DELETE http://localhost:8080/vagas/4
